version: 2.1

executors:
  python-executor:
    working_directory: ~/mmi-reranking-dialoGPT
    docker:
      - image: circleci/python:3.7

jobs:
  run-test:
    executor: python-executor
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            virtualenv env
            . env/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "env"

  check-linting:
    executor: python-executor
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            virtualenv env
            . env/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "env"

      - run:
          name: Run black, flake8, isort
          command: |
            . env/bin/activate
            black --check generation
            flake8 generation
            isort -c generation

workflows:
  version: 2
  python-37-workflow:
    jobs:
      - run-test
      - check-linting
